version: "2"
services:
  stack-viz:
    build:
      context: ./stack-viz
    volumes:
      - './stack-viz:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - PROXY_HOST=${DOCKER_HOST}
      - PROXY_PORT=8080
      
  stream-proxy:
    build:
      context: ./stream-proxy
    volumes:
      - './stream-proxy/src:/app/src'
      - '/app/node_modules'
    ports:
      - '8000:8000'
      - '8080:8080'
    environment:
      - NODE_ENV=development