version: "3.5"
services:
  stack-viz:
    build:
      context: ./stack-viz
    volumes:
      - './stack-viz:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true